/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    testimonials: Testimonial;
    faqs: Faq;
    formSubmissions: FormSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    formSubmissions: FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * “home” for the homepage. Nested paths allowed, e.g. industries/home-services
   */
  slug: string;
  /**
   * Reorder, add, or remove sections — no code needed.
   */
  layout?:
    | (
        | HeroBlock
        | PainPointsBlock
        | StepsBlock
        | AudioSampleBlock
        | ChecklistBlock
        | FeaturesGridBlock
        | CardGridBlock
        | ContentSplitBlock
        | CtaBandBlock
        | AccordionBlock
        | LogoMarqueeBlock
        | DemoCallFormBlock
        | SchedulerEmbedBlock
        | NumberedListBlock
        | RichTextBlockType
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant?: ('home' | 'inner') | null;
  eyebrow?: string | null;
  heading: string;
  /**
   * Blank line = new paragraph. **text** = bold.
   */
  body?: string | null;
  primaryCta?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  /**
   * Floating chips orbiting the Voice Orb (home variant only)
   */
  chips?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PainPointsBlock".
 */
export interface PainPointsBlock {
  heading: string;
  intro?: string | null;
  cards?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'painPoints';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  layout?: ('cards' | 'rows') | null;
  steps?:
    | {
        title: string;
        /**
         * Blank line = new paragraph. **text** = bold.
         */
        body?: string | null;
        groups?:
          | {
              /**
               * Optional intro line above the list
               */
              label?: string | null;
              items?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        closing?: string | null;
        link?: {
          label?: string | null;
          /**
           * e.g. /request-a-free-demo or #sample
           */
          href?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudioSampleBlock".
 */
export interface AudioSampleBlock {
  heading: string;
  /**
   * Blank line = new paragraph. **text** = bold.
   */
  body?: string | null;
  /**
   * e.g. “Listen to a Sample:”
   */
  label?: string | null;
  /**
   * TODO: replace with an industry-specific recording where available
   */
  audio?: (number | null) | Media;
  caption?: string | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'audioSample';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers (or the audio for context)
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistBlock".
 */
export interface ChecklistBlock {
  heading?: string | null;
  /**
   * Blank line = new paragraph. **text** = bold.
   */
  body?: string | null;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'checklist';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesGridBlock".
 */
export interface FeaturesGridBlock {
  heading: string;
  intro?: string | null;
  tiles?:
    | {
        title: string;
        body?: string | null;
        icon?:
          | (
              | 'phone'
              | 'clock'
              | 'chat'
              | 'chart'
              | 'globe'
              | 'plug'
              | 'scale'
              | 'calendar'
              | 'route'
              | 'shield'
              | 'bolt'
              | 'note'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuresGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Show sequential mono numbers on cards
   */
  numbered?: boolean | null;
  /**
   * Compact 4-up sub-cards
   */
  small?: boolean | null;
  cards?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  closing?: string | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  link?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentSplitBlock".
 */
export interface ContentSplitBlock {
  eyebrow?: string | null;
  heading: string;
  /**
   * Blank line = new paragraph. **text** = bold.
   */
  body?: string | null;
  groups?:
    | {
        /**
         * Optional intro line above the list
         */
        label?: string | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  closing?: string | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  link?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock".
 */
export interface CtaBandBlock {
  style?: ('plain' | 'gradient') | null;
  heading: string;
  /**
   * Blank line = new paragraph. **text** = bold.
   */
  body?: string | null;
  cta?: {
    label?: string | null;
    /**
     * e.g. /request-a-free-demo or #sample
     */
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  heading?: string | null;
  intro?: string | null;
  items?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Emit FAQPage JSON-LD for these items
   */
  faqSchema?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoMarqueeBlock".
 */
export interface LogoMarqueeBlock {
  heading?: string | null;
  caption?: string | null;
  groups?:
    | {
        label?: string | null;
        /**
         * TODO: replace text wordmarks with real logo assets
         */
        names?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoMarquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DemoCallFormBlock".
 */
export interface DemoCallFormBlock {
  heading: string;
  /**
   * Blank line = new paragraph. **text** = bold.
   */
  body?: string | null;
  formHeading?: string | null;
  nameLabel?: string | null;
  phoneLabel?: string | null;
  agentLabel?: string | null;
  agents?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  consentText?: string | null;
  checkboxLabel?: string | null;
  submitLabel?: string | null;
  successMessage?: string | null;
  errorMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'demoCallForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SchedulerEmbedBlock".
 */
export interface SchedulerEmbedBlock {
  heading?: string | null;
  /**
   * TODO: paste the scheduling embed URL (Calendly / GHL). Empty = reserved placeholder.
   */
  embedUrl?: string | null;
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'schedulerEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedListBlock".
 */
export interface NumberedListBlock {
  heading?: string | null;
  intro?: string | null;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'numberedList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockType".
 */
export interface RichTextBlockType {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: string | null;
  publishedAt?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Feeds the social-proof strip once real testimonials exist.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  role?: string | null;
  company?: string | null;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable Q&A — pull into pages via the Accordion block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every demo-call and contact submission lands here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formSubmissions".
 */
export interface FormSubmission {
  id: number;
  formType: 'demo-call' | 'contact';
  name: string;
  phone: string;
  email?: string | null;
  /**
   * Chosen AI agent / industry
   */
  agent?: string | null;
  message?: string | null;
  consent?: boolean | null;
  /**
   * Page the form was submitted from
   */
  sourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'formSubmissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        painPoints?: T | PainPointsBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        audioSample?: T | AudioSampleBlockSelect<T>;
        checklist?: T | ChecklistBlockSelect<T>;
        featuresGrid?: T | FeaturesGridBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        contentSplit?: T | ContentSplitBlockSelect<T>;
        ctaBand?: T | CtaBandBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        logoMarquee?: T | LogoMarqueeBlockSelect<T>;
        demoCallForm?: T | DemoCallFormBlockSelect<T>;
        schedulerEmbed?: T | SchedulerEmbedBlockSelect<T>;
        numberedList?: T | NumberedListBlockSelect<T>;
        richText?: T | RichTextBlockTypeSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  chips?:
    | T
    | {
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PainPointsBlock_select".
 */
export interface PainPointsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  layout?: T;
  steps?:
    | T
    | {
        title?: T;
        body?: T;
        groups?:
          | T
          | {
              label?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
        closing?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudioSampleBlock_select".
 */
export interface AudioSampleBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  label?: T;
  audio?: T;
  caption?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistBlock_select".
 */
export interface ChecklistBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesGridBlock_select".
 */
export interface FeaturesGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  tiles?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  numbered?: T;
  small?: T;
  cards?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  closing?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  link?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentSplitBlock_select".
 */
export interface ContentSplitBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  groups?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  closing?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  link?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock_select".
 */
export interface CtaBandBlockSelect<T extends boolean = true> {
  style?: T;
  heading?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock_select".
 */
export interface AccordionBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  faqSchema?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoMarqueeBlock_select".
 */
export interface LogoMarqueeBlockSelect<T extends boolean = true> {
  heading?: T;
  caption?: T;
  groups?:
    | T
    | {
        label?: T;
        names?:
          | T
          | {
              name?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DemoCallFormBlock_select".
 */
export interface DemoCallFormBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  formHeading?: T;
  nameLabel?: T;
  phoneLabel?: T;
  agentLabel?: T;
  agents?:
    | T
    | {
        label?: T;
        id?: T;
      };
  consentText?: T;
  checkboxLabel?: T;
  submitLabel?: T;
  successMessage?: T;
  errorMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SchedulerEmbedBlock_select".
 */
export interface SchedulerEmbedBlockSelect<T extends boolean = true> {
  heading?: T;
  embedUrl?: T;
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedListBlock_select".
 */
export interface NumberedListBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlockType_select".
 */
export interface RichTextBlockTypeSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  company?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formSubmissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  phone?: T;
  email?: T;
  agent?: T;
  message?: T;
  consent?: T;
  sourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  /**
   * One-line description shown in the footer
   */
  tagline?: string | null;
  logo?: (number | null) | Media;
  logoWhite?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Footer legal line, e.g. “© 2026 All Rights Reserved | SkipDial.ai”
   */
  legalStrip?: string | null;
  poweredBy?: string | null;
  notFound?: {
    title?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?: {
    links?:
      | {
          label: string;
          href?: string | null;
          /**
           * Turns this item into a dropdown
           */
          children?:
            | {
                label: string;
                href: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  footer?: {
    linksLabel?: string | null;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    contactLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  tagline?: T;
  logo?: T;
  logoWhite?: T;
  phone?: T;
  email?: T;
  address?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  legalStrip?: T;
  poweredBy?: T;
  notFound?:
    | T
    | {
        title?: T;
        body?: T;
        ctaLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              href?: T;
              children?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  footer?:
    | T
    | {
        linksLabel?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        contactLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}